import numpy as np
array1 = np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])
print(array1)
print(f"Type of array1 is '{type(array1)}'")
print(f"Shape of array1 is '{array1.shape}'")
array1=array1.reshape(2,2,3)
print(array1)
print(f"Shape of array1 is '{array1.shape}'")
array1=array1.reshape(-1)
print(array1)
print(f"Shape of array1 is '{array1.shape}'")
print(array1[4:8])
print(array1[:3])
print(array1[10:])
array2=array1[4:8]
array1=array1[8:12]
array1=array1*2
print(array1,array2)

array3=np.hstack((array1,array2))
print(array3)
newarr = np.array_split(array3, 3)
print("\n\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])
print("\n\n")
x = np.where(array3%2 == 0)
print(x)
print(array3)
print(np.sort(array3))
